version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: trytofindme
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 5520:8080